version: '3'
services:
  tensorflow:
    build:
      dockerfile: ./tensorflow-dockerfile
      context: ./

    volumes:
      - ./notebooks:/notebooks
      
    ports:
      - 8888:8888
      - 6006:6006
